#!/usr/bin/env bash
set -euo pipefail

CONF="/etc/infra/config.json"

MAP_FILE=$(jq -r '.paths.mikrotik_map_short' "$CONF")
OUT_FILE=$(jq -r '.paths.mikrotik_rsyslog_rules' "$CONF")
LOG_DIR=$(dirname "$(jq -r '.paths.mikrotik_log' "$CONF")")

echo "# AUTOGENERATED: Логи MikroTik по имени" > "$OUT_FILE"

sanitize() {
    echo "$1" | tr -d '\r\n' | sed 's/[^A-Za-z0-9._-]/_/g'
}

while IFS='|' read -r ip name; do
    [ -z "$ip" ] && continue
    [ -z "$name" ] && continue
    fname="$(sanitize "$name")"
    logfile="$LOG_DIR/${fname}.log"

    cat << EOF >> "$OUT_FILE"
if (\$fromhost-ip == "$ip") then {
  action(type="omfile" file="$logfile"
    fileCreateMode="0644" dirCreateMode="0750"
    fileOwner="root" fileGroup="zabbix")
  stop
}
EOF

done < "$MAP_FILE"
